services:
  postgres:
    image: postgres:latest
    container_name: seb_postgres
    restart: always
    environment:
      POSTGRES_USER: webserver
      POSTGRES_PASSWORD: webserver
      POSTGRES_DB: seb_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true  # use existing volume
